coverage:
  status:
    project:
      default:
        target: 80% #overall project/ repo coverage

github_checks:
    annotations: true

flags:
  unittests:
    carryforward: true
  integration:
    paths:
    # per https://docs.codecov.com/docs/carryforward-flags#how-carryforward-flags-work-a-motivating-example
      - ".*"
    carryforward: true
