

[repo]
kind = "preferences"

# Add our built-in recipes (FIXME, add a "resource" repo type for directories we expect to find inside
# our python blob)
# url = "pkg://recipes"
# We now (finally) fetch our recipes from the sister github repo via http - We use tags to bind to
# a particular version of the repo (using ${version} which gets substituted with the current starbash version)
recipe_default = "https://raw.githubusercontent.com/geeksville/starbash-recipes/v${version}"

# Some fields in session metadata we don't want to include in reports or toml because they might leak PII
metadata_blacklist = [
    "SITELONG",
    "SITELAT",
]

# FIXME until doit is merged into main, pull recipes from the the local git submodule
# url = "file:///workspaces/starbash/starbash-recipes"

# [[repo-ref]]

# recipe repos contain recipes (identified by name).  When any sb.toml file references
# a recipe the current path of all sources is searched to find that named recipe.

# the standard config includes a few key recipe repos, but interested users or tool
# vendors can define/provide their own

# add a place to find FOO.sb.toml files
# url = "http://fixme.com/foo-repo/somedir"

# test data.  Moved to user preferences (where it should should have been all along)
# [[repo-ref]]
# dir = "~/Pictures/telescope/from_astroboy"
# or inband?


# allow including multiple recipes FIXME old idea, not sure if needed.
# [[repo-ref]]

# looks for a file with this name and .py for the code and .toml for the config
# we'll expect that toml file to contain various [[recipe.*]] sections which will be loaded at this
# location in the sequence as if they were defined here
#by-file = "process-osc-dual-duo"
#by-url = "http:..."

# known equipment vendors and models.  You can update locally or send in a PR to add new ones.  
# FIXME possibly share access to a central repo of known equipment.

[[equipment]]
type = "camera"
vendor = "ZWO"
model.short = "Seestar S50"
fits.instrumen = "Seestar S50" # must match the FITS header INSTRUME field for this camera if you want auto matching.
url.info = "https://us.seestar.com/products/seestar-s50"
subtype = "Seestar" # must match an alias in the [aliases] section for this camera if you want auto matching.

[[equipment]]
type = "camera"
vendor = "ZWO"
model.short = "ASI2600MC Duo"
fits.instrumen = "ZWO ASI2600MC Duo" # must match the FITS header INSTRUME field for this camera if you want auto matching.
url.info = "https://www.zwoastro.com/product/asi2600mc-duo/"
subtype = "OSC" # must match an alias in the [aliases] section for this camera if you want auto matching.

[[equipment]]
type = "filter"
vendor = "sharpstar"
fits.filter = "SiiOiii" # must match the FITS header FILTER field for this filter if you want auto matching.
model.short = "CM-E2"
model.long = "Sharpstar Colour Magic Ultra E2 Duo Narrowband Filter (OIII&SII)"
url.info = "https://www.sharpstar-optics.com/Products_1/CM_E2.html"
subtype = "SiiOiii"

[[equipment]]
type = "filter"
vendor = "Optolong"
fits.filter = "HaOiii" # must match the FITS header FILTER field for this filter if you want auto matching.
model.short = "lult-200"
model.long = "Optolong L-Ultimate 2-inch Dual-Band Filter"
url.info = "https://www.highpointscientific.com/optolong-l-ultimate-2-light-pollution-dual-band-filter-lult-200"
subtype = "HaOiii"

[[equipment]]
type = "filter"
vendor = "Optolong"
fits.filter = "HaOiii" # must match the FITS header FILTER field for this filter if you want auto matching.
model.short = "lext-200"
model.long = "Optolong 2-inch L-Extreme Dual Band 7nm Ha+Oiii Filter"
url.info = "https://www.highpointscientific.com/optolong-2-inch-l-extreme-dual-band-7nm-ha-oiii-filter-lxt-200"
subtype = "HaOiii"

[[equipment]]
type = "mount"
vendor = "Juwei"
model.short = "j17"
model.long = "Juwei J17 Mount"
url.info = "https://www.cloudynights.com/forums/topic/918425-juwei-17-mounts-on-aliexpress/"

[[equipment]]
type = "filterwheel"
vendor = "ZWO"
fits.fwheel = "EFW" # must match the FITS header FWHEEL field if you want auto matching.
model.short = "efw-5x2"
model.long = "ZWO EFW 5x2 Filter Wheel"
url.info = "https://www.zwoastro.com/product/efw-filter-wheels/"

[[equipment]]
type = "telescope"
vendor = "Askar"
fits.telescop = "Askar V.*" # note regexes are supported for fits.x matching
model.short = "Askar V"
model.long = "Askar V APO Refractor"
url.info = "https://www.highpointscientific.com/askar-v-60mm-and-80mm-apo-refractor-w-accessories"

[aliases]
# aliases can be used to map non standard (or non english) frame names to standard terms
# This is also used to map filters based on common misspellings or variations.
# We assume the first listed option in the list is the 'canonical' name used for printing etc...

# frame types
dark = ["dark", "darks"]
flat = ["flat", "flats"]
bias = ["bias", "biases"]
light = ["light", "lights"]

# file suffixes
fits = ["fits", "fit"]

# filter names
SiiOiii = ["SiiOiii", "S2O3"]

# Duo is the name Dwarf3 uses for their HaOiii filter
HaOiii = ["HaOiii", "HaO3", "Duo"]

# Filter names for none/clear filters
# Astro is the name Dwarf3 uses for their IR cut filter
# VIS is the name Dwarf3 uses for their 'clear' filter
# IRCUT/LP are the names Seestar uses for their filters
None = ["None", "Astro", "IRCUT", "LP", "VIS"]

camera_osc = ["OSC", "ZWO ASI2600MC Duo"]
camera_seestar = ["Seestar", "Seestar S50", "Seestar S30", "Seestar S30 Pro"]

# Passes SII 672.4nm and H-Beta 486.1nm lines
# Capturing of the two main emission wavebands in the deep red and blue at the same time
#
# The ALP-T dual band 3.5nm SII&Hb filter is a dual narrowband filter, which lets the deep
# red Sulfur-II 672.4nm and the blue Hydrogen-Beta 486.1nm lines through and is primarily
# engineered for color cameras to assist astrophotographers taking deep sky images with
# superior SNR(Signal to Noise Ratio). With an FWHM halfbandwidth designed at 3.5nm and
# achieving an optical density (OD) of 4.5 on unwanted wavelengths, it works strongly in
# blocking light pollution, moonlight, and airglow, leding to enhanced contrast in nebulae
# images by effectively passing the SII and H-beta emission lines signal only.
#
# http://www.antliafilter.com/pd.jsp?fromColId=2&id=160#_pp=2_671
SiiHb = ["SiiHb", "S2Hb"]


# List the initial search path to find other repos, when the app launches it always first loads this sb.toml file and this file should list all of the
# standard default repo locations.  When searching repos, repos listed LAST have precedence, so target file can override the root processing defaults,
# then the user prefs, then a live github URL or whatever
