# pyright: reportUndefinedVariable=false


import logging
import os
from pathlib import Path
from typing import Any

from starbash.exception import NotEnoughFilesError
from starbash.siril.import_registration import parse_siril_conversion, parse_siril_seq
from starbash.tool import tools

siril = tools["siril"]

# ('context' and 'logger' are normally injected by the starbash runtime)
context: dict[str, Any] = {}
logger: logging.Logger = None  # type: ignore


def _update_ha_registration_metrics() -> None:
    """Parse the merged Ha sequence and update its original source images."""
    updater = context.get("update_image_metadata")
    logger.info(
        "Registration update: updater=%s process_dir=%s source_map=%s",
        updater is not None,
        context.get("process_dir"),
        len(context.get("ha_registration_source_by_name", {})),
    )
    if updater is None:
        logger.warning("Siril registration metadata updater is not configured; skipping")
        return

    sequence_path = Path(context["process_dir"]) / "all_r_Ha_bkg_pp_light_.seq"
    try:
        source_by_name = context.get("ha_registration_source_by_name", {})
        if not isinstance(source_by_name, dict):
            raise ValueError("Missing Ha registration source-name mapping")
        logger.debug("Registration update: parsing %s", sequence_path)
        results = parse_siril_seq(sequence_path)
        conversions = parse_siril_conversion(
            sequence_path.with_name("all_r_Ha_bkg_pp_light_conversion.txt")
        )
        logger.debug(
            "Registration update: parsed %d results and %d conversion mappings",
            len(results),
            len(conversions),
        )
        if len(conversions) != len(results):
            raise ValueError(
                f"Siril returned {len(results)} registration rows for "
                f"{len(conversions)} conversion mappings"
            )
        updates = {}
        for result, conversion in zip(results, conversions, strict=True):
            if not result.selected:
                continue
            source_id = source_by_name.get(Path(conversion.source_name).name)
            if source_id is None:
                source_id = source_by_name.get(conversion.merged_name)
            if source_id is None:
                raise ValueError(f"No database image for {conversion.source_name}")
            updates[source_id] = result.as_metadata()

        expected_count = sum(result.selected for result in results)
        assert len({result.sequence_index for result in results}) == len(results)
        assert len(set(updates)) == len(updates)
        assert len(updates) == expected_count
        if len(updates) != expected_count:
            raise ValueError(
                f"Mapped {len(updates)} selected images, expected {expected_count}"
            )
        updated_count = updater(updates)
        assert updated_count == expected_count
        logger.info("Registration update: updated %d source image records", updated_count)
    except Exception as exc:
        logger.warning("Unable to update Siril registration metadata: %s", exc)


def fix_sequence_name(path: str) -> str:
    """sequence files often have a _.seq suffix, if present we remove that to make siril happy"""
    base = os.path.basename(path)
    if base.endswith("_.seq"):
        base = base[: -len("_.seq")]
    return base


def make_stacked(inputs_to_use: list[Any], variant: str | None, output_file: str) -> None:
    """
    Registers and stacks all pre-processed light frames for a given filter configuration
    across all sessions.
    """
    commands = """
        """

    # If we are being invoked for simple/non duo filter we won't have variants generated by prior steps in the workflow
    if variant is None:
        input_base = "in"  # Starbash has premerged for us
        registration_input = input_base
        commands += f"""
        cd {input_base}
        link {input_base} -out=..
        cd ..
        """
    else:
        input_base = f"r_{variant}_bkg_pp_light"

        # The sequence name for all frames of this variant across all sessions
        # e.g. Ha_bkg_pp_light_cHaOiii
        merged_seq_base = f"all_{input_base}"

        # Absolute path for the output stacked file
        stacked_output_path = f"{context['output'].base}/{output_file}.fit"

        # Merge all frames (from multiple sessions and configs) use those for stacking
        seqs_to_merge = []
        for input_name in inputs_to_use:
            ci = context["input"]
            cur_seq = ci.get(input_name)
            if cur_seq:
                seqs_to_merge.extend(cur_seq.short_paths)

        # We only want to process seqs_to_merge for our CURRENT variant.  So drop any files that don't start with that
        # fixme-ai be extra careful for doc/design/fwhm.md because this will change the mapping back to the original files
        seqs_to_merge = [fix_sequence_name(s) for s in seqs_to_merge if s.startswith(input_base)]

        logger.info(f"Registering and stacking for {variant} -> {stacked_output_path}")
        if len(seqs_to_merge) < 1:
            raise NotEnoughFilesError("Need at least one sequence to merge")

        if len(seqs_to_merge) == 1:
            registration_input = seqs_to_merge[0]
            commands += """
            """
        else:
            registration_input = merged_seq_base  # we want later stages to use our merged output
            commands += f"""
            merge {" ".join(seqs_to_merge)} {merged_seq_base}
            """

    # Siril commands for registration and stacking. We run this in process_dir.
    commands += f"""
        # We use -2pass to select the best possible reference frame for others to register against
        # because that frame might get filtered out which breaks stacking.
        register {registration_input} -2pass

        # we use framing=max/min/cog so that registration is not wrt the first frame
        # because we are using -2pass we must complete the registration here before stacking
        # FIXME make drizzle optional
        # note: it is better to do filtering at this stage than when stacking,
        # because it keeps a record of which frames were dropped
        seqapplyreg {registration_input} -drizzle -framing=cog -filter-wfwhm=80% -filter-round=80% -filter-bkg=80%

        # Winsorized Sigma Clipping (w 3 3) with Average rejection to nuke airplane/satellite trails.
        # Trail pixels are bright statistical outliers vs same pixel in other frames, so sigma high 3.0
        # rejects them and averages dark sky from other frames into those spots. Gold standard for >15-20 frames.
        # If faint ghost survives, lower sigma high to 2.5. Previous GESDT method kept for reference:
        # stack r_{registration_input} rej g 0.3 0.05 -filter-wfwhm=3k -norm=addscale -output_norm -32b -out={output_file}
        #stack r_{registration_input} rej w 3 3 -filter-wfwhm=3k -norm=addscale -output_norm -32b -out={output_file}
        stack r_{registration_input} rej w 3 3 -norm=addscale -output_norm -32b -out={output_file}

        # and flip if required
        mirrorx_single {output_file}
        """

    siril.run(commands, context=context, cwd=context["process_dir"])

def make_renormalize(channel_num: int) -> None:
    """
    Aligns the stacked images (Sii, Ha, OIII) and renormalizes Sii and OIII
    to match the flux of the Ha channel.
    """
    logger.info("Aligning and renormalizing stacked images.")

    # Define file basenames for the stacked images created in the 'process' directory
    ha_base = "results_00001"
    oiii_base = "results_00002"
    sii_base = "results_00003"

    # Define final output paths. The 'results' directory is a symlink in the work dir.
    results_dir = context["output"].base
    os.makedirs(results_dir, exist_ok=True)

    commands = ""

    if channel_num == 1:
        # Only one channel - just copy it - eventually we'll add other metadata
        final_path = f"{results_dir}/stacked.fits"
        commands += f"""
            load results_00001
            save "{final_path}"
            """

    # Basenames for registered files (output of 'register' command)
    r_ha = f"r_{ha_base}"
    r_oiii = f"r_{oiii_base}"

    if channel_num >= 2:
        # Do pixelmath to fixup channel brightness
        logger.info("Doing renormalisation of extra Ha/Oiii channels")

        ha_final_path = f"{results_dir}/stacked_Ha.fits"
        oiii_final_path = f"{results_dir}/stacked_OIII.fits"

        # Pixel math formula for renormalization.
        # It matches the median and spread (MAD) of a channel to a reference channel (Ha).
        # Formula: new = old * (MAD(ref)/MAD(old)) - (MAD(ref)/MAD(old)) * MEDIAN(old) + MEDIAN(ref)
        pm_oiii = f'"${r_oiii}$*mad(${r_ha}$)/mad(${r_oiii}$)-mad(${r_ha}$)/mad(${r_oiii}$)*median(${r_oiii}$)+median(${r_ha}$)"'

        # Siril commands to be executed in the 'process' directory
        commands += f"""
            # -transf=shift fails sometimes, which I guess is possible because we have multiple sessions with possible different camera rotation
            # -interp=none also fails sometimes, so let default interp happen
            # -drizzle is required for success on many images
            # FIXME - I don't thing this register is required anymore
            # we do it in earlier stages.  But leaving now until I can test
            register results -drizzle
            pm {pm_oiii}
            update_key FILTER Oiii "OSC Duo filter extracted"
            save "{oiii_final_path}"
            load {r_ha}
            update_key FILTER Ha "OSC Duo filter extracted"
            save "{ha_final_path}"
            """

    if channel_num >= 3:
        logger.info("Doing renormalisation of extra Sii channel")

        sii_final_path = f"{results_dir}/stacked_Sii.fits"
        r_sii = f"r_{sii_base}"
        pm_sii = f'"${r_sii}$*mad(${r_ha}$)/mad(${r_sii}$)-mad(${r_ha}$)/mad(${r_sii}$)*median(${r_sii}$)+median(${r_ha}$)"'
        commands += f"""
            pm {pm_sii}
            update_key FILTER Sii "OSC dual Duo filter extracted"
            save "{sii_final_path}"
            """

    siril.run(commands, context=context, cwd=context["process_dir"])
    logger.info(f"Saved final renormalized images to {results_dir}")


def osc_process(has_ha_oiii: bool, has_sii_oiii: bool) -> None:
    """Shared code for use by OSC processing scripts"""

    logger.info(f"Running osc_process(has_ha_oiii={has_ha_oiii}, has_sii_oiii={has_sii_oiii})")
    logger.debug("Using context: %s", context)

    channel_num = 0
    if has_sii_oiii:
        # red output channel - from the SiiOiii filter Sii is on the 672nm red channel (mistakenly called Ha by siril)
        channel_num += 1
        make_stacked(["sii"], "Ha", f"results_{channel_num:05d}")

    if has_ha_oiii:
        # green output channel - from the HaOiii filter Ha is on the 656nm red channel
        channel_num += 1
        make_stacked(["ha"], "Ha", f"results_{channel_num:05d}")
        ha_input = context.get("input", {}).get("ha")
        if ha_input is not None and getattr(ha_input, "provenance", None):
            context["ha_registration_source_by_name"] = ha_input.provenance
            logger.info(
                "Registration update: captured %d Ha provenance entries",
                len(ha_input.provenance),
            )
        else:
            logger.warning("Registration update: Ha input has no provenance entries")
        _update_ha_registration_metrics()

    if has_ha_oiii or has_sii_oiii:
        # blue output channel - both filters have Oiii on the 500nm blue channel.  Note the case here is uppercase to match siril output
        channel_num += 1
        make_stacked(["ha", "sii"], "OIII", f"results_{channel_num:05d}")

    # if we haven't already processed some other way - just do a single channel process
    # FIXME in this case we want to use a siril line like "stack r_bkg_pp_light rej g 0.3 0.05 -filter-wfwhm=3k -norm=addscale -output_norm -rgb_equal -32b -out=result"
    if channel_num == 0:
        # single channel - just stack all Ha frames together
        channel_num += 1
        # Use the default/anonymous 0 input name
        make_stacked([0], None, f"results_{channel_num:05d}")

    # There might be an old/state autogenerated .seq file, delete it so it doesn't confuse renormalize
    results_seq_path = f"{context['process_dir']}/results_.seq"
    if os.path.exists(results_seq_path):
        os.remove(results_seq_path)

    assert channel_num >= 1, "At least one channel should have been processed"
    make_renormalize(channel_num)
